### ISSUE TITLE
HTML error

### ISSUE THREAD

**Issue by conneralegre** [wbajem01/prj-rev-bwfs-tea-cozy#2]
Important for errors - Line 6 of `index.html` is missing the closing `/>` which is causing HTML errors. We'll want to make sure we always close our elements appropriately so it's suggested to use something like an HTML validator or HTML linter to avoid these errors. Here is an HTML validator from the official W3C: https://validator.w3.org/#validate_by_input

**Comment by wbajem01** [comment]
Rookie mistake that one.
