### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by conneralegre** [wbajem01/prj-rev-bwfs-tea-cozy#5]
Grade: **Meets Expectations**

This project is looking and working great! I really liked how clean your HTML and CSS were as they follow good style guidelines. The usage of semantic elements is also very great to see as this is also best practices and important for organization. A couple of recommendations to improve this project:

* Use an HTML validator to make sure there are no HTML errors
* Add alt attributes to your images for accessibility purposes

Overall, nice work!

**Comment by wbajem01** [comment]
Thanks very much!
